name: Docker - Build and Push

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set short git commit SHA
        id: vars
        run: echo "COMMIT_SHORT_SHA=$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_ENV
      - name: Build and push
        if: github.GITHUB_REF_NAME != 'main'
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ env.COMMIT_SHORT_SHA }}:${{ steps.vars.outputs.sha_short}},${{ env.COMMIT_SHORT_SHA }}:dev
      - name: Build and push
        if: github.GITHUB_REF_NAME == 'main'
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ env.COMMIT_SHORT_SHA }}:${{ steps.vars.outputs.sha_short}},${{ env.COMMIT_SHORT_SHA }}:latest
